"""Add enable_transcript_validation to interview_session

Revision ID: 03daf0b2b565
Revises: 0007
Create Date: 2026-06-02 03:23:52.064891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '03daf0b2b565'
down_revision: Union[str, None] = '0007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_pipeline_runs_celery_task_id'), table_name='ai_pipeline_runs')
    op.drop_column('ai_pipeline_runs', 'celery_task_id')
    op.drop_column('interview_evaluations', 'low_confidence_reasons')
    op.add_column('interview_sessions', sa.Column('enable_transcript_validation', sa.Boolean(), nullable=False, server_default='false', comment='Optional: validate transcript compatibility with JD'))
    op.drop_index(op.f('idx_applications_version_status'), table_name='job_applications')
    op.drop_index(op.f('ix_job_applications_candidate_id'), table_name='job_applications')
    op.drop_index(op.f('ix_job_applications_job_version_id'), table_name='job_applications')
    op.drop_index(op.f('ix_job_versions_job_id'), table_name='job_versions')
    op.drop_index(op.f('idx_job_status_created'), table_name='jobs')
    op.drop_constraint(op.f('fk_media_session'), 'media_files', type_='foreignkey')
    op.drop_column('media_files', 'session_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_files', sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_media_session'), 'media_files', 'interview_sessions', ['session_id'], ['id'])
    op.create_index(op.f('idx_job_status_created'), 'jobs', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_job_versions_job_id'), 'job_versions', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_applications_job_version_id'), 'job_applications', ['job_version_id'], unique=False)
    op.create_index(op.f('ix_job_applications_candidate_id'), 'job_applications', ['candidate_id'], unique=False)
    op.create_index(op.f('idx_applications_version_status'), 'job_applications', ['job_version_id'], unique=False)
    op.drop_column('interview_sessions', 'enable_transcript_validation')
    op.add_column('interview_evaluations', sa.Column('low_confidence_reasons', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('ai_pipeline_runs', sa.Column('celery_task_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_ai_pipeline_runs_celery_task_id'), 'ai_pipeline_runs', ['celery_task_id'], unique=False)
    # ### end Alembic commands ###
