"""auto_update_schema

Revision ID: 89887a30fdc4
Revises: 0005
Create Date: 2026-05-13 02:16:11.171174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89887a30fdc4'
down_revision: Union[str, None] = '0005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evaluation_criteria', sa.Column('is_mandatory', sa.Boolean(), nullable=False))
    op.create_foreign_key('fk_media_session', 'media_files', 'interview_sessions', ['session_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_media_session', 'media_files', type_='foreignkey')
    op.drop_column('evaluation_criteria', 'is_mandatory')
    # ### end Alembic commands ###
