"""remove_enable_transcript_validation

Revision ID: e3c3d62438b1
Revises: 03daf0b2b565
Create Date: 2026-06-03 11:22:45.450342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3c3d62438b1'
down_revision: Union[str, None] = '03daf0b2b565'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview_sessions', 'enable_transcript_validation')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_sessions', sa.Column('enable_transcript_validation', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False, comment='Optional: validate transcript compatibility with JD'))
    # ### end Alembic commands ###
